# Generated by Django 4.1.6 on 2023-02-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guest',
            new_name='no_guest',
        ),
    ]
